### PR TITLE
Rework to allow instanciation

### PR DESCRIPTION
**Pull request by elwinar**
Here is the code from the repository deleted somewhere in time.

### CODE REVIEW

**Comment by elwinar** [comment]
This branch should be editable by any maintainer.

I'll start reading what was added since then, to know what I should add.

**Comment by elwinar** [comment]
I can't understand what choice led to the library counting what it logs…

**Comment by elwinar** [comment]
Note: given that all the things done with this lib seem related to Hugo in one way or another, why not simply include the lib in Hugo and let this one die softly ?

**Comment by bep** [comment]
>I can't understand what choice led to the library counting what it logs…

The count itself is not interesting, knowing if "an ERROR has been logged" is interesting. I'm not pulling this code into Hugo.

**Comment by elwinar** [comment]
Knowing if an error has been logged is pointless.
What you want is to know if an error occurred, which shouldn't be the 
job of the logging library.

Anyway, the library itself is lackluster, and the code from my pull 
request out-of-date by 2 years, I don't think rebasing it is worth the 
time it will take me to come up to speed with the actual code.
You can do it if you want, but while I believe that the global way of 
doing things is right either, the actual jww isn't going in the right 
direction.

**Comment by bep** [comment]
>Knowing if an error has been logged is pointless.
>What you want is to know if an error occurred, which shouldn't be the
>job of the logging library.

That is a pretty bold statement. I would love keep this PR open, grap some popcorn and see where this discussion is going. But I have other stuff to do. Thanks for your valuable contribution.

**Pull request closed without merging**
