### PR TITLE
Reworked to enable instantiation

### PR DESCRIPTION
**Pull request by elwinar**
I  reworked JWW into a simple `Notepad` structure that
more or less handle all the job by itself.

The old interface of JWW is almost conserved, using a `Notepad` created
in the `init()` and whose `loggers` are linked to exported vars, and
relinked when changes occurs. I'm not really satisfied by this solution,
but it's simple and efficient, and leave the external API clean.

There is one API break, that is to take a `io.Writer` instead of a path for
the log output. I feel it simpler and it evacuate the need to check for
errors in the lib, and enable the end-user to do some really cool things
quite simply (like logging to a database, etc).

I also enabled the user to choose flags and an optional prefix, like the
original `log.Logger` struct… it is useful to distinguish two Notepad's
outputs.

### CODE REVIEW

**Comment by bep** [comment]
Sorry for the lack of response to this one. Is the motivation to have several jww logger instances in one application?

This PR needs a rebase and the CLA needs to be signed.

**Comment by elwinar** [comment]
It was my intention. I've deleted the repo since, but it should not be that hard to redo. I'll give it a try this week-end if I manage to wake up.

**Comment by bep** [comment]
@elwinar I plan on getting rid of the Hugo globals in the near future, and then this is one of the fixes I need ... :-)

**Comment by elwinar** [comment]
I've just signed the license agreement, I'll do the rebase as soon as possible.

**Comment by bep** [comment]
@elwinar any updates on this?

I plan on "getting rid of all the globals in Hugo" -- and this logger is one of them.

https://github.com/spf13/hugo/issues/2701

**Comment by bep** [comment]
OK, I will fix it myself.

**Comment by elwinar** [comment]
Just came home from work, I'll do it tonight. I let this drag on too long.

**Comment by elwinar** [comment]
Here is already the code in the state it was at the time : https://github.com/spf13/jWalterWeatherman/pull/14

**Pull request closed without merging**
